### PR TITLE
add .idea into .gitignore, remove duplication, add shebang line in lo…

### PR DESCRIPTION
**Pull request by andantonyan**
…cal_env

### CODE REVIEW

**Comment by svenstaro** [comment]
Why remove the target ignore? And what's .idea?

**Comment by andantonyan** [comment]
There was a two target in .gitignore file, and .idea for intellij project configuration files

**Comment by svenstaro** [comment]
Ok cool, merging. Thanks for the PR!

On a different note: Are you actually using this boilerplate? It's basically undocumented and was made mostly for personal use. If people are actually interested, I might set it up more properly.

**Comment by andantonyan** [comment]
Thanks you too. Currently I am just using it for learning purpose, maybe on the future I will start to add some new functionalities. Good project :)

**Pull request merged**
